"""Are sessions generated STEPWISE (one teacher turn per step, state evolves coherently from
its own outputs) statistically the same as sessions generated by a SINGLE whole-session prompt?

Generates N coherent sessions/persona each way via the OpenRouter teacher, validates both vs
the funnel.py anchors, and prints the per-(persona,step) conditional churn + conversion + ε
side by side.  python -m research.compare_gen --N 40 --workers 48
"""
import argparse, random, time
from concurrent.futures import ThreadPoolExecutor

from uniqa.persona_datagen import LLMTeacher, generate_feed
from research.run import validate, PERSONAS
from uniqa.funnel import ABANDON_PROBS, Step

CELLS = [Step.PERSONAL_INFO, Step.TARIFF_SELECT, Step.PERSONAL_DATA]


def gen(teacher, N, workers, seed):
    by = {}
    for p in PERSONAS:
        with ThreadPoolExecutor(max_workers=workers) as ex:
            by[p] = list(ex.map(lambda i: generate_feed(p, teacher, random.Random(seed + i)), range(N)))
    return validate(by)


def row(rep, p):
    d = rep["personas"][p]
    cb = d["cond_bounce"]
    return (d["conv_rate"], [cb.get(s.value) for s in CELLS])


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--N", type=int, default=40)
    ap.add_argument("--workers", type=int, default=48)
    ap.add_argument("--seed", type=int, default=900)
    args = ap.parse_args(argv)

    methods = {
        "single_prompt":   LLMTeacher(stepwise=False, include_params=True),
        "stepwise_rollout": LLMTeacher(stepwise=True, include_params=True, include_state=True),
    }
    reps = {}
    for name, t in methods.items():
        t0 = time.time()
        reps[name] = gen(t, args.N, args.workers, args.seed)
        print(f"[{name}] N={args.N}/persona in {time.time()-t0:.1f}s  "
              f"ε={reps[name]['overall']['epsilon_mean_abs_bounce']}  "
              f"conv_w={reps[name]['overall']['obs_conv_weighted']}")

    print("\n=== per-(persona,step) conditional churn  [single | stepwise | target] + conversion ===")
    for p in PERSONAS:
        cs, (cv_s, bs_s) = None, row(reps["single_prompt"], p)
        cv_w, bs_w = row(reps["stepwise_rollout"], p)
        print(f"\n {p}:  conv  single={cv_s:.3f}  stepwise={cv_w:.3f}")
        for i, s in enumerate(CELLS):
            tgt = ABANDON_PROBS[p].get(s)
            a, b = bs_s[i], bs_w[i]
            astr = f"{a:.2f}" if a is not None else "—"
            bstr = f"{b:.2f}" if b is not None else "—"
            diff = (f"|Δ|={abs(a-b):.2f}" if (a is not None and b is not None) else "")
            print(f"    {s.value:18} single={astr}  stepwise={bstr}  target={tgt:.2f}  {diff}")

    es, ew = reps["single_prompt"]["overall"], reps["stepwise_rollout"]["overall"]
    print(f"\nε: single={es['epsilon_mean_abs_bounce']}  stepwise={ew['epsilon_mean_abs_bounce']}  (gate 0.12)")
    print(f"weighted conv: single={es['obs_conv_weighted']}  stepwise={ew['obs_conv_weighted']}")


if __name__ == "__main__":
    raise SystemExit(main())
